#OBJS specifies which files to compile as part of the project
OBJS = main.cpp

#OBJ_NAME specifies the name of our exectuable
OBJ_NAME = asteroids

#This is the target that compiles our executable
all : $(OBJS)
	g++ $(OBJS) -w -lsfml-graphics -lsfml-window -lsfml-system -o $(OBJ_NAME)
